### ISSUE TITLE
Not available on maven central

### ISSUE THREAD

**Issue by hshar7** [intuit/graphql-filter-java#7]
Can't sync maven project with this dependency because this package is not available anywhere not jitpack or maven central

**Comment by Saturas89** [comment]
I am also interested.

**Comment by jaiswalsk** [comment]
We are working on getting this resolved. will update here once its is fixed.

**Comment by jaiswalsk** [comment]
Snapshot version 1.0.0-SNAPSHOT has been released and should be available to consume. Release version 1.0.0 should be available soon. Thanks for your patience!

**Comment by jaiswalsk** [comment]
Release version 1.0.0 has been published to central nexus repository. Closing this issue. https://repo1.maven.org/maven2/com/intuit/graphql/graphql-filter-java/1.0.0/
